### ISSUE TITLE
Plugin not working as intended

### ISSUE THREAD

**Issue by RareMaker50** [ItemsAdder/ItemsAdderBlocksInjector#3]
Basically I'm following the steps in the IA Wiki but the server won't work
I have all the dependencies (Block Injector, Itemsadder, iris, Protocollib, ViaVersion) and boot up the server with Itemsadder blocks in the iris  configs, but this error keeps coming up: https://bin.bloom.host/emadiwejed
before I had like a 250k long server crash error

I asked in the Iris server and they said my config looks perfectly fine, I also used the test config on the IA wiki and it didn't work

Every time I reinstall all the configs packs and retry I get a different error, usually it's either something like this: https://bin.bloom.host/huyusixoli
or the server crashing, or it generating a corrupt world because it can't load it for some reason, works fine once I remove the itemsadder arguments

1 of the configs I used: https://bin.bloom.host/oyamobevow.yaml

It simply just won't work

**Comment by thefourcraft** [comment]
# about IA and Iris 
IA compatibility with iris is new so bugs will happen as far as I can see the config looks fine...
## clear some things up... 
First I suggest you to try finding bugs with [mc logs](https://mclo.gs/)
# try 
Did you join the server to see the world? 

I will take a better look at this because I also use ia and iris on my server and I have no problems...

**Comment by RareMaker50** [comment]
Did you join the server to see the world?
Yes, It was a completely corrupt world after all those errors
I will take a better look at this because I also use ia and iris on my server and I have no problems...
Alright thank you, do you have ores generated and you can see the ores? because I tried this on a completely fresh server with just those 5 plugins with fresh configs and everything and I'm dealing with the same issue

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/171142314-84a23c17-8f5c-4b11-ba6d-51da31fa3853.png)

![immagine](https://user-images.githubusercontent.com/27242001/171142431-6f64daff-2925-499f-ac95-b500154f7978.png)


Somehow Iris is loading before ItemsAdderBlocksInjector in your server.
This is probably the cause of the error.

Create a folder called `ItemsAdderBlocksInjector` inside your plugins folder and add [this file](https://github.com/ItemsAdder/ItemsAdderBlocksInjector/blob/master/itemsadder-blocks-injector-core/src/main/resources/config.yml), then set `debug: true` and send the log here.
To download the file press the `RAW` button.

Or just create a config.yml file and write `debug: true`

**Comment by thefourcraft** [comment]
# Troubleshooting🤔 
I am using Iris and IA & block injector with no problems, I have tested also the Iris core to the MAX and I had no problems.
So, it appears that you have a bug, we need to find what is the bug that is causing your problem.
## Steps OF Troubleshooting 🔍 
### Update everything 🙃 
Server Software\
Iris\
Placeholder API \
ViaVision \
Iteamadder \
the IA block Injecter
### Reset the world ⭕ 
regain the iris world with the most up do date overworld configuration. also make sure that you are configuring the IA with Iris the right way, if the config is wrong nothing is going to work.
Also, don't forget to [follow the full tutorial on the Iris wiki...](https://docs.volmit.com/iris/getting-started) and ask for support on their [discord server](https://discord.com/invite/volmit) if you have any problems
### Timings Report ⌚ 
make a timings report, it will give @LoneDev6 and me (@thefourcraft) more information about the problem...
[How To Make A Timing Report?](https://shockbyte.com/billing/knowledgebase/198/How-to-Take-a-Timings-Report-on-Your-Minecraft-Server.html) | [How To Read A Timing report...](https://shockbyte.com/billing/knowledgebase/220/How-to-Analyze-a-Timings-v2-Report.html)
### More Logs 📚 
Provide more logs about the problem...
try different configurations and try using the latest 2 updates for each plugin... if one update works share the log for it
also, your client log would be helpful also... 
[How To Get My Client Log?](https://shockbyte.com/billing/knowledgebase/328/How-to-Find-and-Share-Any-Minecraft-Log.html)
### Home testing 🏠 
make a test server at home and see if you have the same problem... maybe it's a host problem, we had the most bizarre problem on bunngecord and the fix was not related to Minecraft at all 
https://github.com/SpigotMC/BungeeCord/issues/3276
### Configs 😄 
Share all the configs... server, IA, Iris, and any config that is connected to IA and the block injector 
## Personal Opinion🍖 
I think that if everything is configured correctly you need more RAM or something... Iris is very unstable and needs a lot of RAM to be stable I don't need a lot of RAM because it's efficient and fast.\

**IF YOU WANT** to add the send this to the iris dev ([this GitHub issue](https://github.com/ItemsAdder/ItemsAdderBlocksInjector/issues/3)) and ask them what they think about it\
we are all on the same page and just want to improve our software 🤝

**Comment by RareMaker50** [comment]
Alright so I have 10gb of ram, is this enough? I'm gonna try a home test with fresh configs and everything and see what happens and I have used fresh worlds several times. Everything is on the latest snapshot version with regenerated configs. I think the bug is that ItemsAdder_Block_Injector is loading after Item adder and iris are loading so that is what the bug seems to be since iris can't figure out what block (for example) iasurvival:amethyst_ore is and everything goes downhill from there.

**Comment by NextdoorPsycho** [comment]
> # Troubleshooting🤔
> I am using Iris and IA & block injector with no problems, I have tested also the Iris core to the MAX and I had no problems. So, it appears that you have a bug, we need to find what is the bug that is causing your problem.
> 
> ## Steps OF Troubleshooting 🔍
> ### Update everything 🙃
> Server Software Iris Placeholder API ViaVision Iteamadder the IA block Injecter
> 
> ### Reset the world ⭕
> regain the iris world with the most up do date overworld configuration. also make sure that you are configuring the IA with Iris the right way, if the config is wrong nothing is going to work. Also, don't forget to [follow the full tutorial on the Iris wiki...](https://docs.volmit.com/iris/getting-started) and ask for support on their [discord server](https://discord.com/invite/volmit) if you have any problems
> 
> ### Timings Report ⌚
> make a timings report, it will give @LoneDev6 and me (@thefourcraft) more information about the problem... [How To Make A Timing Report?](https://shockbyte.com/billing/knowledgebase/198/How-to-Take-a-Timings-Report-on-Your-Minecraft-Server.html) | [How To Read A Timing report...](https://shockbyte.com/billing/knowledgebase/220/How-to-Analyze-a-Timings-v2-Report.html)
> 
> ### More Logs 📚
> Provide more logs about the problem... try different configurations and try using the latest 2 updates for each plugin... if one update works share the log for it also, your client log would be helpful also... [How To Get My Client Log?](https://shockbyte.com/billing/knowledgebase/328/How-to-Find-and-Share-Any-Minecraft-Log.html)
> 
> ### Home testing 🏠
> make a test server at home and see if you have the same problem... maybe it's a host problem, we had the most bizarre problem on bunngecord and the fix was not related to Minecraft at all [SpigotMC/BungeeCord#3276](https://github.com/SpigotMC/BungeeCord/issues/3276)
> 
> ### Configs 😄
> Share all the configs... server, IA, Iris, and any config that is connected to IA and the block injector
> 
> ## Personal Opinion🍖
> I think that if everything is configured correctly you need more RAM or something... Iris is very unstable and needs a lot of RAM to be stable I don't need a lot of RAM because it's efficient and fast.\
> 
> **IF YOU WANT** to add the send this to the iris dev ([this GitHub issue](https://github.com/ItemsAdder/ItemsAdderBlocksInjector/issues/3)) and ask them what they think about it we are all on the same page and just want to improve our software 🤝

This was so well formatted im about to look like a tard with GIT even though ive been using it for over 10 years. i literally cant compete with this level of formatting. 

Having said that we can try making iris Softdepend on IABI and see if that works @ me on discord and ill give it a try

**Comment by thefourcraft** [comment]
@NextdoorPsycho well it's not that hard, you just need the right tools :)
I recommend taking a look at [this amazing repo](https://github.com/rzashakeri/beautify-github-profile)
# About ℹ️ 
The Repository made by [rzashakeri](https://github.com/rzashakeri) has all the possible configurations for readme files which you can learn a lot from it... 
The Repository has a lot of tips on the markdown format and a lot of cool amazing things to improve your GIt experience
## About Me 🤗 
I know git because I'm a translator for things and apps, I had translated over 60+ projects on [Crowdin](https://crowdin.com/) & Some GitHub
if you take a look at my [README.MD ](https://github.com/thefourcraft) 🦈 
### Just Some Stats 📊 
projects: 63
strings: 100M+
some projects that I worked on I can't disclose because of confidentiality agreements 🍸 
__My biggest ones__
Minecraft Java Edition
Minecraft Bedrock Edition
Minecraft Education Edition
Minecraft Windows 10 Edition
Minecraft API Docs
Minecraft Xbox Edition
Minecraft Dungeons
OBS
Crowdin - work in progress
